### PR TITLE
Modified manifests

### PR DESCRIPTION
**Pull request by gnpaone**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by Macleykun** [comment]
so should i retry over ath winget-pkgs to get this merged or want me to wait for smth else?

**Comment by gnpaone** [comment]
> so should i retry over ath winget-pkgs to get this merged or want me to wait for smth else?

I think maybe wait for settings parameter? Or else settings maybe postponed to other release and publishing first can be given importance so I think retrying is the best option. For me installer got successfully installed in sandbox.

**Comment by gnpaone** [comment]
Hey @Macleykun I have gone through the manifest files yesterday as well as others manifest files too, I didn't find anything wrong. I have a way to troubleshoot this issue. I have created #2 so that the installer opens as normal installer if working correctly or shows the exact error in installer as a dialog box if not working properly. You must have seen this https://github.com/rcmaehl/MSEdgeRedirect/issues/28#issuecomment-1048510646 right, check the first screenshot, if error in installer then it shows like that. Can you also ask for the vm screenshot with this error dialog box

**Comment by gnpaone** [comment]
> Hey @Macleykun I have gone through the manifest files yesterday as well as others manifest files too, I didn't find anything wrong. I have a way to troubleshoot this issue. I have created #2 so that the installer opens as normal installer if working correctly or shows the exact error in installer as a dialog box if not working properly. You must have seen this [rcmaehl/MSEdgeRedirect#28 (comment)](https://github.com/rcmaehl/MSEdgeRedirect/issues/28#issuecomment-1048510646) right, check the first screenshot, if error in installer then it shows like that. Can you also ask for the vm screenshot with this error dialog box Older Run logs: [InstallationVerificationLogs (1).zip](https://github.com/Macleykun/winget-pkgs/files/8138348/InstallationVerificationLogs.1.zip) Latest Run logs: [InstallationVerificationLogs (2).zip](https://github.com/Macleykun/winget-pkgs/files/8138351/InstallationVerificationLogs.2.zip)

See, There was an error popup (need mods help with the screenshot of the dialog box I guess)
[InstallationVerificationLogs (4).zip](https://github.com/Macleykun/winget-pkgs/files/8139194/InstallationVerificationLogs.4.zip)
InstallationVerification-x64-machine-Locale_Undefined-ErrorScreenshot_20220225065845

**Comment by gnpaone** [comment]
Hey @Macleykun , created #4 to revert changes. I understood the problem causing the error. https://github.com/rcmaehl/MSEdgeRedirect/issues/28#issuecomment-1050960335

**Pull request merged**
